### PR TITLE
 Try to use whatever libpng version is present

### PR DESCRIPTION
**Pull request by ljosa**

### CODE REVIEW

**Comment by ljosa** [comment]
@xach, could you please give this a try?

**Comment by quicklisp** [comment]
Builds fine, but I get this (during tests?): 

    CONVOLVE-EDGE: Error opening #P"/home/quicklisp/quicklisp-controller/dist/build-cache/cl-png/c9e27d12ee0e08c1dd2823fa5c28813e65b2b719/cl-png-vl-anyversion-7d0cf5b6-git/test/images/butterfly8-gray.png": No such file or directory

**Comment by quicklisp** [comment]
Also, I had been using cl-png 0.6 from your website, which does not include image.asd. But there is another Quicklisp project called "image" that provides image.asd. I can update cl-png but the image system will not be visible via Quicklisp.

**Comment by ljosa** [comment]
Thanks, I’ll take another look.

**Comment by quicklisp** [comment]
It turns out the image.asd problem is bigger than I realized. Since I have to block cl-png's image.asd, cl-png tries to work with a completely unrelated system also named `image`. That in turn means cl-png can't work as-is.

Would you consider renaming the cl-png image system to something else?

**Comment by ljosa** [comment]
@quicklisp, I don't mind getting rid of the "image" system at all. (In fact, the reason I hadn't finished this up yet is that I couldn't figure out a workable way to have multiple systems.) I've removed it now and also made the tests run. Could you please see if this works for you?

**Comment by epsilon-phase** [comment]
@ljosa This pull request appears to work on my system, if that's any help.

**Pull request merged**
